FROM --platform=${TARGETPLATFORM:-linux/amd64} rust:alpine AS builder
RUN apk update
RUN apk add libusb-dev musl-dev git

ENV LOCAL=/usr/local
ENV RUSTFLAGS=-Ctarget-feature=+aes,+ssse3
# ENV CARGO_BUILD_TARGET=x86_64-unknown-linux-gnu
# ENV TMKMS_VERSION=v0.12.2

WORKDIR /root
RUN git clone https://github.com/iqlusioninc/tmkms.git
WORKDIR /root/tmkms
RUN cargo build --release --features=softsign

# The production image starts here
FROM --platform=${TARGETPLATFORM:-linux/amd64} alpine

COPY --from=builder /root/tmkms/target/release/tmkms ${LOCAL}/bin

ENTRYPOINT [ "tmkms" ]