// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: jomtx/jomtx/txn.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Txn struct {
	Id        uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	InvoiceNo string   `protobuf:"bytes,2,opt,name=invoiceNo,proto3" json:"invoiceNo,omitempty"`
	Proofs    []string `protobuf:"bytes,3,rep,name=proofs,proto3" json:"proofs,omitempty"`
	Items     string   `protobuf:"bytes,4,opt,name=items,proto3" json:"items,omitempty"`
	Remarks   string   `protobuf:"bytes,5,opt,name=remarks,proto3" json:"remarks,omitempty"`
	Files     []string `protobuf:"bytes,6,rep,name=files,proto3" json:"files,omitempty"`
	Creator   string   `protobuf:"bytes,7,opt,name=creator,proto3" json:"creator,omitempty"`
	Customer  string   `protobuf:"bytes,8,opt,name=customer,proto3" json:"customer,omitempty"`
	Total     uint64   `protobuf:"varint,9,opt,name=total,proto3" json:"total,omitempty"`
	Currency  string   `protobuf:"bytes,10,opt,name=currency,proto3" json:"currency,omitempty"`
	Decimals  uint32   `protobuf:"varint,11,opt,name=decimals,proto3" json:"decimals,omitempty"`
}

func (m *Txn) Reset()         { *m = Txn{} }
func (m *Txn) String() string { return proto.CompactTextString(m) }
func (*Txn) ProtoMessage()    {}
func (*Txn) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e1dca766e541e53, []int{0}
}
func (m *Txn) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Txn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Txn.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Txn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Txn.Merge(m, src)
}
func (m *Txn) XXX_Size() int {
	return m.Size()
}
func (m *Txn) XXX_DiscardUnknown() {
	xxx_messageInfo_Txn.DiscardUnknown(m)
}

var xxx_messageInfo_Txn proto.InternalMessageInfo

func (m *Txn) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Txn) GetInvoiceNo() string {
	if m != nil {
		return m.InvoiceNo
	}
	return ""
}

func (m *Txn) GetProofs() []string {
	if m != nil {
		return m.Proofs
	}
	return nil
}

func (m *Txn) GetItems() string {
	if m != nil {
		return m.Items
	}
	return ""
}

func (m *Txn) GetRemarks() string {
	if m != nil {
		return m.Remarks
	}
	return ""
}

func (m *Txn) GetFiles() []string {
	if m != nil {
		return m.Files
	}
	return nil
}

func (m *Txn) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *Txn) GetCustomer() string {
	if m != nil {
		return m.Customer
	}
	return ""
}

func (m *Txn) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Txn) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *Txn) GetDecimals() uint32 {
	if m != nil {
		return m.Decimals
	}
	return 0
}

func init() {
	proto.RegisterType((*Txn)(nil), "jomtx.jomtx.Txn")
}

func init() { proto.RegisterFile("jomtx/jomtx/txn.proto", fileDescriptor_4e1dca766e541e53) }

var fileDescriptor_4e1dca766e541e53 = []byte{
	// 288 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0xbd, 0x4e, 0xc3, 0x30,
	0x14, 0x85, 0xeb, 0xf4, 0x37, 0xae, 0x60, 0xb0, 0x00, 0x5d, 0x21, 0x64, 0x45, 0x0c, 0x28, 0x53,
	0x2b, 0x51, 0x21, 0x56, 0xc4, 0x03, 0x30, 0x44, 0x4c, 0x6c, 0xa9, 0xe3, 0x82, 0x21, 0x8e, 0x23,
	0xdb, 0x85, 0xf4, 0x2d, 0x58, 0x78, 0x27, 0xc6, 0x8e, 0x8c, 0x28, 0x79, 0x11, 0x14, 0x3b, 0x0d,
	0xcb, 0x95, 0xbe, 0x73, 0xcf, 0xb9, 0xd2, 0x3d, 0xf8, 0xf4, 0x55, 0x49, 0x5b, 0x2d, 0xfd, 0xb4,
	0x55, 0xb1, 0x28, 0xb5, 0xb2, 0x8a, 0xcc, 0x9d, 0xb0, 0x70, 0xf3, 0xf2, 0x2b, 0xc0, 0xc3, 0xc7,
	0xaa, 0x20, 0xc7, 0x38, 0x10, 0x19, 0xa0, 0x08, 0xc5, 0xa3, 0x24, 0x10, 0x19, 0xb9, 0xc0, 0xa1,
	0x28, 0xde, 0x95, 0x60, 0xfc, 0x41, 0x41, 0x10, 0xa1, 0x38, 0x4c, 0xfe, 0x05, 0x72, 0x86, 0x27,
	0xa5, 0x56, 0x6a, 0x63, 0x60, 0x18, 0x0d, 0xe3, 0x30, 0xe9, 0x88, 0x9c, 0xe0, 0xb1, 0xb0, 0x5c,
	0x1a, 0x18, 0xb9, 0x84, 0x07, 0x02, 0x78, 0xaa, 0xb9, 0x4c, 0xf5, 0x9b, 0x81, 0xb1, 0xd3, 0x0f,
	0xd8, 0xfa, 0x37, 0x22, 0xe7, 0x06, 0x26, 0xee, 0x8c, 0x87, 0xd6, 0xcf, 0x34, 0x4f, 0xad, 0xd2,
	0x30, 0xf5, 0xfe, 0x0e, 0xc9, 0x39, 0x9e, 0xb1, 0xad, 0xb1, 0x4a, 0x72, 0x0d, 0x33, 0xb7, 0xea,
	0xb9, 0xbd, 0x65, 0x95, 0x4d, 0x73, 0x08, 0xdd, 0x13, 0x1e, 0x7c, 0x42, 0x6b, 0x5e, 0xb0, 0x1d,
	0xe0, 0x43, 0xc2, 0x73, 0xbb, 0xcb, 0x38, 0x13, 0x32, 0xcd, 0x0d, 0xcc, 0x23, 0x14, 0x1f, 0x25,
	0x3d, 0xdf, 0xdf, 0x7d, 0xd7, 0x14, 0xed, 0x6b, 0x8a, 0x7e, 0x6b, 0x8a, 0x3e, 0x1b, 0x3a, 0xd8,
	0x37, 0x74, 0xf0, 0xd3, 0xd0, 0xc1, 0xd3, 0xd5, 0xb3, 0xb0, 0x2f, 0xdb, 0xf5, 0x82, 0x29, 0xb9,
	0xfc, 0x90, 0xe6, 0xfa, 0x66, 0x75, 0xdb, 0x55, 0xdc, 0x57, 0xbd, 0x2b, 0xb9, 0x59, 0x4f, 0x5c,
	0xdb, 0xab, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xee, 0xc3, 0x62, 0x0d, 0x86, 0x01, 0x00, 0x00,
}

func (m *Txn) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Txn) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Txn) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Decimals != 0 {
		i = encodeVarintTxn(dAtA, i, uint64(m.Decimals))
		i--
		dAtA[i] = 0x58
	}
	if len(m.Currency) > 0 {
		i -= len(m.Currency)
		copy(dAtA[i:], m.Currency)
		i = encodeVarintTxn(dAtA, i, uint64(len(m.Currency)))
		i--
		dAtA[i] = 0x52
	}
	if m.Total != 0 {
		i = encodeVarintTxn(dAtA, i, uint64(m.Total))
		i--
		dAtA[i] = 0x48
	}
	if len(m.Customer) > 0 {
		i -= len(m.Customer)
		copy(dAtA[i:], m.Customer)
		i = encodeVarintTxn(dAtA, i, uint64(len(m.Customer)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTxn(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Files) > 0 {
		for iNdEx := len(m.Files) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Files[iNdEx])
			copy(dAtA[i:], m.Files[iNdEx])
			i = encodeVarintTxn(dAtA, i, uint64(len(m.Files[iNdEx])))
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.Remarks) > 0 {
		i -= len(m.Remarks)
		copy(dAtA[i:], m.Remarks)
		i = encodeVarintTxn(dAtA, i, uint64(len(m.Remarks)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Items) > 0 {
		i -= len(m.Items)
		copy(dAtA[i:], m.Items)
		i = encodeVarintTxn(dAtA, i, uint64(len(m.Items)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Proofs) > 0 {
		for iNdEx := len(m.Proofs) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Proofs[iNdEx])
			copy(dAtA[i:], m.Proofs[iNdEx])
			i = encodeVarintTxn(dAtA, i, uint64(len(m.Proofs[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.InvoiceNo) > 0 {
		i -= len(m.InvoiceNo)
		copy(dAtA[i:], m.InvoiceNo)
		i = encodeVarintTxn(dAtA, i, uint64(len(m.InvoiceNo)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintTxn(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTxn(dAtA []byte, offset int, v uint64) int {
	offset -= sovTxn(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Txn) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTxn(uint64(m.Id))
	}
	l = len(m.InvoiceNo)
	if l > 0 {
		n += 1 + l + sovTxn(uint64(l))
	}
	if len(m.Proofs) > 0 {
		for _, s := range m.Proofs {
			l = len(s)
			n += 1 + l + sovTxn(uint64(l))
		}
	}
	l = len(m.Items)
	if l > 0 {
		n += 1 + l + sovTxn(uint64(l))
	}
	l = len(m.Remarks)
	if l > 0 {
		n += 1 + l + sovTxn(uint64(l))
	}
	if len(m.Files) > 0 {
		for _, s := range m.Files {
			l = len(s)
			n += 1 + l + sovTxn(uint64(l))
		}
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTxn(uint64(l))
	}
	l = len(m.Customer)
	if l > 0 {
		n += 1 + l + sovTxn(uint64(l))
	}
	if m.Total != 0 {
		n += 1 + sovTxn(uint64(m.Total))
	}
	l = len(m.Currency)
	if l > 0 {
		n += 1 + l + sovTxn(uint64(l))
	}
	if m.Decimals != 0 {
		n += 1 + sovTxn(uint64(m.Decimals))
	}
	return n
}

func sovTxn(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTxn(x uint64) (n int) {
	return sovTxn(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Txn) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTxn
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Txn: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Txn: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTxn
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InvoiceNo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTxn
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTxn
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTxn
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InvoiceNo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proofs", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTxn
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTxn
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTxn
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proofs = append(m.Proofs, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Items", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTxn
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTxn
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTxn
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Items = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Remarks", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTxn
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTxn
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTxn
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Remarks = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Files", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTxn
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTxn
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTxn
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Files = append(m.Files, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTxn
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTxn
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTxn
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Customer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTxn
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTxn
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTxn
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Customer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Total", wireType)
			}
			m.Total = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTxn
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Total |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Currency", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTxn
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTxn
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTxn
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Currency = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Decimals", wireType)
			}
			m.Decimals = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTxn
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Decimals |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTxn(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTxn
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTxn(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTxn
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTxn
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTxn
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTxn
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTxn
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTxn
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTxn        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTxn          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTxn = fmt.Errorf("proto: unexpected end of group")
)
